EMS/Models/Department.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace EMS.Models;

public partial class Department
{
    public int Id { get; set; }
    [Display(Name = "Department Name")]
    [Required(ErrorMessage ="Department Name cannot Blank")]
    public string DeptName { get; set; } = null!;
    [Display(Name="City")]
    [StringLength(25,MinimumLength =3,ErrorMessage ="City must be 3 Chars")]
    public string Location { get; set; } = null!;

    public virtual ICollection<Employee> Employees { get; set; } = new List<Employee>();
}

EMS/Models/DobCheck.cs
using System.ComponentModel.DataAnnotations;
namespace EMS.Models;
public class DobCheck:ValidationAttribute
{
    public override bool IsValid(object value)
    {
        DateTime birthdate=Convert.ToDateTime(value);
        int year=birthdate.Year;
        int currentyear=DateTime.Now.Year;
        if(currentyear - year >=25)
            return true;
        else
            return false;
    }
}

EMS/Models/Employee.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
namespace EMS.Models;

public partial class Employee
{
    public int EmpId { get; set; }
    [Required(ErrorMessage ="Name is Required")]
    public string Name { get; set; } = null!;
    [Range(10000,90000,ErrorMessage ="Salary between 10000 and 90000")]
    public int Salary { get; set; }
    [Display(Name="Department")]
    public int DeptId { get; set; }
    [Display(Name="Email")]
    [DataType(DataType.EmailAddress)]
    public string Email { get; set; } = null!;
    [DataType(DataType.Date)]
    [DisplayFormat(ApplyFormatInEditMode =true,DataFormatString ="{0:yyyy-mm-dd}")]
    [DobCheck(ErrorMessage ="You Should be 25 year of age to work in LTI")]
    public DateTime Dob { get; set; }
    public virtual Department Dept { get; set; } = null!;
}

EMS/Models/EmsDbContext.cs
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;
using Microsoft.EntityFrameworkCore.SqlServer;

namespace EMS.Models;

public partial class EmsDbContext : DbContext
{
    public virtual DbSet<Employee>Employees {get;set;} 
    public virtual DbSet<Department> Departments {get;set;} 
    public EmsDbContext()
    {
    }

    public EmsDbContext(DbContextOptions<EmsDbContext> options)
        : base(options)
    {
    }


    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    

        => optionsBuilder.UseSqlServer("User ID=sa;password= examlyMssql@123;server=localhost;Database=EmsDb;trusted_connection=false; Persist Security Info=False;Encrypt=false;");
    


    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Department>(entity =>
        {
            entity.ToTable("Department");

            entity.Property(e => e.DeptName).HasMaxLength(30);
            entity.Property(e => e.Location)
                .HasMaxLength(30)
                .HasColumnName("location");
        });

        modelBuilder.Entity<Employee>(entity =>
        {
            entity.HasKey(e => e.EmpId);

            entity.HasIndex(e => e.DeptId, "IX_Employees_DeptId");

            entity.HasIndex(e => e.Email, "IX_Employees_Email").IsUnique();

            entity.Property(e => e.Dob).HasColumnName("DOB");
            entity.Property(e => e.Email).HasMaxLength(40);
            entity.Property(e => e.Name).HasMaxLength(30);

            entity.HasOne(d => d.Dept).WithMany(p => p.Employees).HasForeignKey(d => d.DeptId);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}

EMS/Models/ErrorViewModel.cs
namespace EMS.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

EMS/Controllers/DeptController.cs
using Microsoft.AspNetCore.Mvc;
using EMS.Models;
namespace EMS.Controllers;
public class DeptController:Controller
{
    private readonly EmsDbContext context;
    public IActionResult Display(int id)
    {
        var data=context.Employees.Where(e=>e.DeptId==id);
        return View(data);
    }
    public DeptController(EmsDbContext _context)
    {
      context=_context;  
    }
public IActionResult List()
{
    List<Department> data=null;
    try
    {
        data=context.Departments.ToList();
        if(data.Count==0)
        throw new Exception();

    }
    catch(System.Exception){
        ViewBag.ErrorMessage="0 records present";
        return View("Error");
    }
    //var data=context.Departments.ToList();
    return View(data);
}
public IActionResult Create()
{
    return View();
}
[HttpPost]
public IActionResult Create(Department department)
{
    if(ModelState.IsValid)
    {
        context.Departments.Add(department);
        context.SaveChanges();
        return RedirectToAction("List");
    }
    return View();
}
}

EMS/Controllers/EmpController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EMS.Models;
namespace EMS.Controllers;
public class EmpController:Controller
{
    private readonly EmsDbContext context;
    public EmpController(EmsDbContext _context)
    {
      context=_context;  
    }


public IActionResult List()
{
    var data=context.Employees.Include("Dept").ToList();
    return View(data);
}
public IActionResult Create()
{
    ViewBag.DeptId=new SelectList(context.Departments,"Id","DeptName");
    return View();
}
[HttpPost]
public IActionResult Create(Employee emp)
{
    //if(ModelState.IsValid)
    {
        context.Employees.Add(emp);
        context.SaveChanges();
        return RedirectToAction("List");
    }
    ViewBag.DeptId=new SelectList(context.Departments,"Id","DeptName");
    return View(emp);
}
}

EMS/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using EMS.Models;

namespace EMS.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

EMS/Views/Dept/Create.cshtml
@model Department
<h2>Adding Department</h2>
<hr>
@using(Html.BeginForm())
{
    <div class="form-horizontal">
        @Html.ValidationSummary(true,"",new {@class="text-danger"})
        <div class=form-group>
            @Html.DisplayNameFor(d=>d.DeptName)
            @Html.EditorFor(d=>d.DeptName)
        </div>
        <div class=form-group>
            @Html.DisplayNameFor(d=>d.Location)
            @Html.EditorFor(d=>d.Location)
        </div>
    </div>
    <br>
    <br>
    <input type="submit" value="Save" class="btn btn-default">
}
<br>
@Html.ActionLink("Back","List")

EMS/Views/Dept/Display.cshtml
@model IEnumerable<Employee>
<table class='table'>
    <thead>
        <th>@Html.DisplayNameFor(e=>e.EmpId)</th>
        <th>@Html.DisplayNameFor(e=>e.Name)</th>
        <th>@Html.DisplayNameFor(e=>e.Salary)</th>
        <th>@Html.DisplayNameFor(e=>e.Email)</th>
        <th>@Html.DisplayNameFor(e=>e.Dob)</th>
    </thead>
    <tbody>
        @foreach(var data in Model)
        {
            <tr>
                <td>@Html.DisplayFor(e=>data.EmpId)</td>
                <td>@Html.DisplayFor(e=>data.Name)</td>
                <td>@Html.DisplayFor(e=>data.Salary)</td>
                <td>@Html.DisplayFor(e=>data.Email)</td>
                <td>@Html.DisplayFor(e=>data.Dob)</td>
            </tr>
        }
    </tbody>
</table>
<br><br>
<a asp-controller="Home" asp-action="Index">Home</a>

EMS/Views/Dept/List.cshtml
@model IEnumerable<Department>
    <div class='container'>
        <h1>Department Listing</h1>
        <h3>@Html.ActionLink("Add Department","Create")</h3>
        <br>
        <table class="table table-bordered">
            <thead>
                <th>@Html.DisplayNameFor(d=>d.Id)</th>
                <th>@Html.DisplayNameFor(d=>d.DeptName)</th>
                <th>@Html.DisplayNameFor(d=>d.Location)</th>
            </thead>
            <tbody>
                @foreach(var dept in @Model)
                {
                    <td>@dept.Id</td>
                    <td>@dept.DeptName</td>
                    <td>@dept.Location</td>
                    <td></td>
                    <td>
                        @Html.ActionLink("Details","Display",new{id=dept.Id}) &nbsp;&nbsp;
                        @Html.ActionLink("Edit","Edit",new{id=dept.Id}) &nbsp;&nbsp;
                        @Html.ActionLink("Delete","Delete",new{id=dept.Id}) &nbsp;&nbsp;
                    </td>
                }
            </tbody>
        </table>
    </div>

EMS/Views/Emp/Create.cshtml
@model Employee
<div class="jumbotron">
    <form method="post">
        <label asp-for="Name"></label>
        <input type='text' asp-for='Name'>
        <span asp-validation-for="Name" style="color:red"></span>
        <br><br>
        <label asp-for="Salary"></label>
        <input type='text' asp-for='Salary'>
        <span asp-validation-for="Salary" style="color:red"></span>
        <br><br>
        <label>Select Departments</label>
        <select asp-for="DeptId" asp-items="ViewBag.DeptId">
            <option value=''>Choose Departments</option>
        </select>
        <br><br>
        <label asp-for="Email"></label>
        <input type='text' asp-for='Email'>
        <span asp-validation-for="Email" style="color:red"></span>
        <br><br>
        <label asp-for="Dob"></label>
        <input type='date' asp-for='Dob'>
        <br><br>
        <input type='Submit' value='Save' class='btn btn-success'>
    </form>
    <br><br>
    <a asp-asp-controller="Emp" asp-action="List">Back To List</a>
</div>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.jquery-validation-unobtrusive.min.js"></script>

EMS/Views/Emp/List.cshtml
@model IEnumerable<Employee>

<h2>Employee Listing</h2>
<hr>
<div style="text-align:right">
<a asp-controller="Emp" asp-action="Create">Add Employee</a>
</div>
<table class="table">
    <thead>
        <th>
            @Html.DisplayNameFor(e=>e.EmpId)
        </th>
        <th>
            @Html.DisplayNameFor(e=>e.Name)
        </th>
        <th>
            @Html.DisplayNameFor(e=>e.Dept.DeptName)
        </th>
        <th>
            @Html.DisplayNameFor(e=>e.Dept.Location)
        </th>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(e=>item.EmpId)</td>
                <td>@Html.DisplayFor(e=>item.Name)</td>
                <td>@Html.DisplayFor(e=>item.Dept.DeptName)</td>
                <td>@Html.DisplayFor(e=>item.Dept.Location)</td>
                <td>
                    <a asp-controller="Employee" asp-action="Display" asp-route-id=item.Id>Display</a>
                </td>
            </tr>           
        }
    </tbody>
</table>

EMS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EMS</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EMS.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <h1>LTI Mindtree</h1>
        <hr>
        <nav style="background-color: greenyellow;text-align:center">
            <a asp-controller="Dept" asp-action="List">Department</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <a asp-controller="Emp" asp-action="List">Employee</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <a asp-controller="Dept" asp-action="Create">Add Department</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - EMS - 
            Contact:<br>
            Lnt Mindtree
            Mahape
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>